language: java
sudo: false

script:
  - mvn clean verify

after_success:
  - mvn clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: mvn clean deploy --settings .travis.settings.xml
  on:
    tags: true

env:
  global:
    - secure: sWga5WvUP6p4IZjq8xKCXUomBmaAb7uCormrlfWWYeXV/LMb8VMqfbgRt7DMlvum+umarxY6VgEwhYHq5lHM0AYDOv7PGap/sj933sb0CjVqmG2N36OEDXeJFtQkxDEIm0VBzt//wzrXTb5cFQPKbiP05Uz3OWgfblhF4Zfd2lodC1bvlD3SLsFvMZ/ajGCf+xFc1WRItI3oWcWtj7Ljc1QlVzJbNmXODlWHLebAfycrLMp53xCdSbbTTsDuXinF26xeYV90wlZL6iIiFOpHsOMAc3c70B+lkit4m3u9C2NExaemUDCShHqbldps90JA4RkJ4qOEZw3StMZ3xn1MTa4FUBMaXsGSleSRvppvqhtRRyqgp6lKRcp4xkJML2yp0YF2EMJAIQkloxqJSa2EcH3ocxOiBhTVg8AJcbRrh1WcEcfn0GZDMywc7YpGiB9agvtjbdG95afxlu3tMQZ8+08ZPSLRJEbD3/S8o5a9AW3Vccgn+tYYdCLbykBlj6rzIIrqReiqnauBaeHn0qyxlp0ZPj0QMtWn7vxqcew1P0cx0VdesJO6kLHaN5xBcXoZQHOiI4bJBa/ZDghdRT6xVdbY4jINJ7ZbOUBDsCDhPcV+jqQaeYxR+Dfpcq4SmBKE7lzZHJfCpmStxNpJWDR2asCSesW24y30KC6aRTckBEQ=
    - secure: SJWnDHtbaOgRPGEB0nLl6k06Fqh+56TqS7az1LHAEzLqEF96tuTsqrRakBmTS8mcZxYTJL+di+F/ikTcwKUJOvSTpn1Z8FiGcJNM6QXo2F6/t02YER10BMxgf19wXthRkyxVR7EN87oVqQKDhSeXs2N3+9TiHeXwteLZOEQCcmsqltPVSJZrCbXt4IOp3j+Dnv7qRbG69se3I4c6T6fYvRR6HLhxy7aertM73yabOw2VwlKLYRAuaK3arT1rVdcyGIZadJ7Y3+iuEvtV2CGZV99cI8tlX86jIPiPZQBcc6gdSAta3ulTZpB8bQmjBeJunZBRTxu1wSPSb6sGWJPMpepvUboiTg5K263AlN/6GwEGWipMsshkcIOsR9BJJ1WS0t19w7QVqKN2DrLk+Q6f8TZ1EsghzAnG73sA63S7LcOzpWxXqWXWjj3gWceaZQNCqS+ZzVr++NxVn6NuHX2i82zV6bFAkhnW3l6kAWrv0zJeTCOE97TEh67Je0Ebo5lwAjKXmNWApHJBVlHkXpEtsR3hElylRMAEQivaYvrcoIsmQCBAdKM+P0rc8eGynxm+AKcXKlHfSafjriqwCPNtVvzWktSPhphIVYgXqYX5z3yxOBHG1y0VpoTLOsoha+zNlgnlcirDUDXhKN0RiKPjX3zJpJs+jeUyMKrZtC9/jW8=
